<?php

return [

    /*
    |--------------------------------------------------------------------------
    | License server
    |--------------------------------------------------------------------------
    */
    'server_url' => env('LICENSE_SERVER_URL', 'https://license.finextsolution.com'),

    /*
    |--------------------------------------------------------------------------
    | Product identity
    |--------------------------------------------------------------------------
    |
    | product_id/bootstrap_key_id/bootstrap_secret are issued once by the
    | license server admin panel (Product → API Keys) and shipped inside
    | this product's source. They only sign the very first /activate call —
    | see README.md for why that's a deliberately weaker guarantee than the
    | per-installation secret generated afterward.
    |
    */
    'product_id' => env('LICENSE_PRODUCT_ID'),
    'bootstrap_key_id' => env('LICENSE_BOOTSTRAP_KEY_ID'),
    'bootstrap_secret' => env('LICENSE_BOOTSTRAP_SECRET'),

    /*
    |--------------------------------------------------------------------------
    | This installation
    |--------------------------------------------------------------------------
    |
    | license_key is entered by the customer (or preset by whoever deploys
    | it). installation_id is generated once on first activation and then
    | persisted — regenerating it would make the server treat this as a
    | brand new installation against the max_activations limit.
    |
    */
    'license_key' => env('LICENSE_KEY'),
    'installation_id_path' => storage_path('app/license/installation-id'),

    /*
    |--------------------------------------------------------------------------
    | Activation secret
    |--------------------------------------------------------------------------
    |
    | Generated by the server on first activation and never shipped in
    | source — this is the real security boundary (see README.md). Stored
    | as plaintext on disk (like the host app's own .env), protected by
    | filesystem permissions (0600) and by living outside version control —
    | it cannot itself be encrypted-at-rest without begging the question of
    | where that encryption key would live.
    |
    */
    'activation_secret_path' => storage_path('app/license/activation-secret'),

    /*
    |--------------------------------------------------------------------------
    | Server public key (Ed25519)
    |--------------------------------------------------------------------------
    |
    | Pinned fallback for first boot / offline verification. The client
    | refreshes this from GET /public-key when reachable and caches it
    | locally, but always falls back to this pinned value so a
    | man-in-the-middle can't silently swap in a different key by
    | intercepting that one unauthenticated endpoint.
    |
    */
    'pinned_key_id' => env('LICENSE_PINNED_KEY_ID', 'v1'),
    'pinned_public_key' => env('LICENSE_PINNED_PUBLIC_KEY'),
    'public_key_cache_path' => storage_path('app/license/public-key.json'),

    /*
    |--------------------------------------------------------------------------
    | Local cache & offline grace period
    |--------------------------------------------------------------------------
    */
    'cache_path' => storage_path('app/license/cache.dat'),
    'default_grace_period_days' => (int) env('LICENSE_DEFAULT_GRACE_PERIOD_DAYS', 3),

    /*
    |--------------------------------------------------------------------------
    | HTTP
    |--------------------------------------------------------------------------
    */
    'timeout_seconds' => (int) env('LICENSE_HTTP_TIMEOUT_SECONDS', 10),

];
